.pre-commit-config.yaml, README.md, api/refiner/dev-requirements.txt, api/trigger-code-reference/dev-requirements.txt, pyproject.toml
This PR adds the `ruff` linter to the project and provides some basic configuration.
Fixes #
- #7 
Please refer to the [`Running the linter` section](https://github.com/CDCgov/dibbs-ecr-refiner/pull/9/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5) in the updated README for setup & testing instructions. Feel free to let me know if these can be improved!
Maybe not the biggest issue since I imagine we'll often be using `ruff` via the `pre-commit` git hook, it would be a lot nicer if we didn't have to install `ruff` in both the `refiner` and the `trigger-code-reference`. However, these are currently two independent projects 😕
Is there a better way to go about this with how things are currently set up?
=> chore: Set up ruff linter locally

docker-compose.yaml
This PR:
1. Makes it so that editing files in `/api/refiner` and `/api/trigger-code-reference` will cause the respective service to reload
2. Makes it so that new files can be added or removed locally and the changes will be reflected in the running container(s)
Fixes #10 
A quick way to understand how this works:
1. From the project root, run `docker compose up`
4. In `api/refiner/app/main.py` try changing the `health_check()`'s return to `{"status": "TEST"}`
5. Save the file and you should see logs that let you know the server has reloaded
6. Hit the API's health check endpoint (`/`) and you should see your modified response
What has been done so far seems to do everything I'd want it to with the way the repo is currently structured. Is there anything else that'd be helpful to change …
=> chore: docker compose hot reloads on file changes

.github/CODEOWNERS
This should solve the issue with folks not getting auto-assigned for PR reviews.
=> chore: fix CODEOWNERS file syntax

api/refiner/app/utils.py
The icd-9 url at some point was removed from the list of expected systems, which was causing an error since those codes were still in the sqlite db. For now, this will keep things working as expected as we think about what the core needs are of a TCR explicitly as it relates to refiner and begin the work of folding the two services into one.
Fixes #14 
- #14 
1. build clean images using `docker compose build --no-cache` at the project root
2. start the services with `docker compose up -d`
3. using the API or rest tool of your choice and a test eICR for the body, `POST` this url: `http://localhost:8080/ecr?conditions_to_include=240589008`
4. if there are any observations connected to this it should be preserved.
=> fix: add the icd-9 url back to the list of expected values

.github/workflows/lint.yml, .github/workflows/pipeline.yml, .github/workflows/tests.yml
This is just a small update to the GitHub Actions to give us a little more flexibility:
- `pipeline.yml` will automatically run when we merge to `main`
- `lint.yml` and `tests.yml` will be able to run on-demand and independently of the pipeline
=> chore: Run pipeline on merge to main, allow individual jobs to run via manual trigger

.github/workflows/pipeline.yml
This PR updates `pipeline.yml` to be triggered when a PR enters the merge queue. It seems this [`merge_group` block is necessary to include](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#status-checks-with-github-actions-and-a-merge-queue) or the jobs will not be kicked off.
Here are the repository settings I've updated as a part of this work:
Fixes #6 
We should be able to try merging this PR. If the jobs aren't kicked off, we can back it out of the queue. Maybe we can also test it with `act`?
=> chore: pipeline should run checks when PR is in merge queue

refiner/assets/refiner_config.json
There are patterns in the RR that differ slightly from the eICR in connection to coded elements that have associated values that needed to be represented by the `refiner_config.json` file.
For example, in the RR where we would look for the `RR1` code, it will also have a `<value>` tag that will describe the reportability status with codes like:
- `RRVS2`: May be reporable
- `RRVS3`: Not reportable
- `RRVS1`: Reportable
- `RRVS4`: No rule met
These have been filled out. Additionally the `"contains"` list for some of the RR entries have better linking for representing how these templates are connected.
Fixes #57
- #57
=> docs: Update `refiner-config.json` with `"value_code"` for RR information

refiner/app/main.py, refiner/app/rr_parser.py
- Update /zip-upload endpoint to parse RR
- Once RR is parsed, it will extract the reportable snomed codes 
- If conditions_to_include is not passed in from caller, it will set it as the reportable snomed code found in the RR 
Fixes #29 
- #29 
-  Refiner code has been modified to read the RR XML
-  Code has been written to find reportable conditions
- All reportable conditions and any other required information is stored (in an in-memory data structure like a dictionary, not a database) for usage
Using postman, hit http://localhost:8080/zip-upload with body containing file that is set to a zip file containing and RR and eICR. I used the MonMothma files for this. Ensure a refined ecr is returned from the refiner
- Started to play around with checking for multiple snomed codes in the RR …
=> [feat] add method to parse RR and extract reportable condition snomed code

client/package-lock.json, client/package.json, client/src/App.test.tsx, client/src/main.tsx, client/src/pages/Demo/Error.tsx, client/src/pages/Demo/Layout.tsx, client/src/pages/Demo/ReportableConditions.tsx, client/src/pages/Demo/RunTest.tsx, client/src/pages/Demo/Success.tsx, client/src/pages/Demo/index.test.tsx, client/src/pages/Demo/index.tsx, client/src/services/demo.ts, refiner/app/routes/demo.py
This PR adds the end-to-end demo flow based on the [designs](https://www.figma.com/design/QK7dVoNaG6qIF52r1imkwY/eCR-Refiner?node-id=221-156&p=f&m=dev). This flow functions very similarly to the way [Query Connector handles its query page](https://github.com/CDCgov/dibbs-query-connector/blob/main/src/app/(pages)/query/page.tsx#L82).
Fixes #55, #61, #68
1. Navigate to [http://localhost:8081/demo](http://localhost:8081/demo)
2. Click `Run test`
3. Click `Refine eCR`
4. You should see the success page which will display the unrefined vs. refined comparison XML view
1. In `/routes/demo.py`, add `raise HTTPException` on line 46 and make sure your server reloads
2. Click `Run test` in the UI
3. You should see the error screen. Click `Try again`, which will take you back to the `Run test` screen
=> feat: Add end-to-end demo UI flow

.github/workflows/build.yml, .github/workflows/docker-build-ghcr.yml, .github/workflows/pipeline.yml
This PR adds two GitHub Actions:
1. `docker-build-ghcr.yml` - Upon merge to `main`, builds a container image tagged `main` and `latest`, and pushes it to the refiner's GitHub Container Registry. This job can also be triggered manually to run on any branch. You can also provide a version number if you want to do that. If you don't use a version number, the image tag will be a sanitized version of your branch's name.
2. `build.yml` - This job will run as part of `pipeline.yml` and will build, but not push, the Docker image. This is primarily just a check to make sure the code in the feature branch is buildable without issues.
Fixes #26
1. See a successful pipeline run [here](https://github.com/CDCgov/dibbs-ecr-refiner/actions/runs/15074417789)
2. See a successful build and push …
=> chore: build Docker image and push to ghcr

.gitignore, client/src/pages/Demo/Success.tsx, client/src/pages/Demo/index.test.tsx, client/src/pages/Demo/index.tsx, client/src/services/demo.ts, refiner/app/api/v1/demo.py, refiner/app/core/app/base.py, refiner/app/main.py, refiner/tests/routes/test_demo.py
This PR adds the ability to allow users to download their refined eCR at the end of the demo flow. The API's `/demo/upload` will now do the following:
1. Refine the eCR located on the server (`monmothma.zip`)
2. Generate a unique token
3. Create and store a refined zip file at (`/refined-ecr/{token}`
4. Store the token and information about the saved file (used for handling file retrieval and expiration)
5. Provide the token as part of the API's response (`refined_download_token`)
These files are stored on the application server itself and must be cleaned up. This will be handled by `run_expired_file_cleanup_task()`, which runs as an async task. This is configured on startup by utilizing FastAPI's `lifespan`.
Fixes #41 
Navigate through the demo flow until you get to the success page. On …
=> feat: download refined demo eCR

.github/workflows/trigger_demo_workflow.yaml
- Added a new GitHub Actions workflow file (trigger_demo_workflow.yaml) to enable manual deployment to the demo environment.
- The workflow accepts inputs for the service name and version, and triggers a secondary GitHub Actions workflow in `dibbs-tf-env`
- This initial PR is to test the permissions and integration with the `dibbs-tf-envs` repo. 
- I'll work directly with the team to customize the trigger as needed.
Once this merges to main:
- Manually trigger the workflow on GitHub.
- Verify that the API call is correctly made with the appropriate payload.
- Check the `dibbs-tf-envs` repo kicks off the appropriate job.
=> feat: add workflow to trigger demo deployment via dispatch event

refiner/app/services/refine.py, refiner/tests/test_service_refine.py
This change enhances the backend to properly extract truly reportable 
conditions following the RR specification requirements. Key changes:
- Add strict `RR11` container validation (cardinality 1..1)
- Implement `RR1`/`RRVS1` determination checks for true reportability
- Ensure SNOMED CT codes with `displayNames` are properly extracted
- Add deduplication of reportable conditions
- Update tests to verify conformance and reportability logic
The implementation now correctly:
- Only returns conditions marked as reportable via `RR1`/`RRVS1`
- Includes required SNOMED CT codes and `displayNames`
- Maintains established json response structure
- Enforces RR spec conformance requirements
- Prevents duplicate conditions in output
Fixes #118 
- #118 
1. Run `docker compose up`
2. Check that both …
=> feat(refine): implement reportable condition extraction per RR spec

client/src/pages/Demo/ReportableConditions.tsx, client/src/pages/Demo/RunTest.tsx, client/src/pages/Demo/Success.tsx, client/src/pages/Demo/index.test.tsx, client/src/pages/Home/index.tsx, refiner/app/api/v1/demo.py
The following content changes have been made:
- (Landing Page) On the landing page, would like the 3rd "How it works" section to read: "The Refiner splits the original eICR into child eICRs - one per reportable condition in the RR - and applies a filter that retains only the information associated with the relevant clinical concept codes identified in the TES for that condition." (bold bit is new)
- (Run Test File Page) Would like the upload test file copy to read: "For this demo, we’ve provided a synthetic eICR/RR pair to test the Refiner that contains two reportable conditions. The "Run test" button below will upload the test files to the Refiner.”
- (Reportable Condition and Refinement Page) Would like the copy on this page to read: "We found the following reportable condition(s) in …
=> style: Demo content updates

README.md, refiner/README.md
The Trigger Code Reference service was removed as a dependency in #19 and
relevant code was integrated into the `refiner/app/db.py` file.
- #19
- an inter-team communication were the catalysts for this change.
Fixes #
- `n/a`
The Mermaid diagram for the software architecture doesn't contain a Trigger
Code Reference service container reference any more. And the linking from the
root `README.md` references the `refiner/README.md` correctly.
Verify that the changes under the AC above are present in the repository.
- [Question about whether our team uses the TCR service container 🔒](https://skylight-hq.slack.com/archives/C08H7EV6M37/p1750776980718729)
=> docs(refiner): Update the diagram & link to steps;

refiner/app/services/refine.py, refiner/app/services/terminology.py, refiner/eCR-CDA-Notes.md, refiner/scripts/query_terminology_db.py, refiner/tests/test_service_refine.py, refiner/tests/test_service_terminology.py
Prior versions of the refiner were only looking for clinical data in `<observation>`s. This updated refactor will now extend this beyond simply the `<observation>`'s `<code code="code">`  but also include the `<value code="code">`. Additionally, we will search in the following locations:
This XPath search strategy is comprehensive and flexible because it will look in:
* `<observation><code code="code">`
* `<observation><value code="code">`
* `<manufacturedProduct><code code="code">`
* `<act><code code="code">`
* `<procedure><code code="code">`
* `<translation code="code">`
This will make sure that we're not over-refining the eICR output. The output in the integration test is still checking against this updated code and is valid.
Fixes #136 
- #136 
Unit tests
1. From the project root make …
=> refactor(refine): Update search and filter logic with XPath; update HTML table output

.justscripts/just/client.just, .justscripts/just/server.just, justfile
1. 💬 build: Move commands & add groups 🏷️ 50ddbb9
1. 💬 build: Add server-related recipes 🏷️ bc55c7c
- n/a
- n/a
We should now be able to see commands like the following:
- `just dev`
- `just client`
- `just server`
Also there should now be groupings when outputting recipes.
=> build: Refactor Just a bit further

client/src/components/Layout/index.tsx, client/src/components/NavigationBar/index.tsx, client/src/components/StatusPill/index.tsx
This PR is a small fix to make sure that the `Configurations` and `Testing` links remain visible on narrow screens. Without this fix they'll disappear when the screen gets too small.
I also included some styling to ensure the pill component's text no longer wraps when displayed on smaller screens.
Here's an example:
=> style: Nav links should display on small screens

docker-compose.yaml, refiner/tests/integration/conftest.py
It was noticed that running the design script would not create `users` and `sessions` table, which means folks were not able to log in due to the app crashing. This PR ensures that the SQL script defining `users` and `sessions` runs when the local DB initializes as part of the Docker Compose setup.
[Confirmed this change worked with the design script](https://skylight-hq.slack.com/archives/C08H7EV6M37/p1753393524963209?thread_ts=1753363138.114949&cid=C08H7EV6M37).
1. Shut down and delete your containers
2. Delete your DB volume to ensure no data remains (Should be called `dibbs-ecr-refiner_pgdata`)
3. Run `docker compose up`
4. You should be able to load up [http://localhost:8081](http://localhost:8081) and log in without performing any other steps prior
=> fix: `users` and `sessions` tables should be created upon DB startup

.github/workflows/pr-security-scan.yml
- New workflow file:` .github/workflows/pr-security-scan.yml `
- PR-triggered scanning: Automatically scans container images on every pull request and merge group event
- Local image scanning: Builds and scans images locally without pushing to GHCR, preventing registry pollution
- Matrix strategy: Parallel scanning of both refiner-app and refiner-lambda images using their respective Dockerfiles
- Trivy integration: Comprehensive vulnerability detection with configurable severity thresholds (CRITICAL, HIGH, MEDIUM)`
- GitHub Security integration: Uploads SARIF reports categorized as pr-scan-refiner-app and pr-scan-refiner-lambda
- PR feedback: Automatic security summary comments on pull requests with scan results and links to detailed reports
- Concurrency control: Prevents multiple scans …
=> Add PR image scanning workflow

refiner/scripts/seed_db.py
It was [noted](https://skylight-hq.slack.com/archives/C08H7EV6M37/p1757002082098679) that some of the condition names displayed by the Refiner UI were being bunched together.
This PR updates the seeding script to check if a condition's `title` is available first and to use that over `name` (when possible) to populate a condition's `display_name` field.
Here are a few conditions I've picked out to help clearly display the change:
Testing the application:
1. Run `docker compose up`
2. Run `just db seed` to run the seeding script
3. In your browser, navigate to [http://localhost:8081](http://localhost:8081) to test the application
4. Try adding a new configuration
5. You'll notice the names in the condition list now look as they should (for example, `COVID-19` instead of `COVID19`)
=> fix: seeding script prefers `title` over `name` for condition's `display_name`

.justscripts/just/database.just
This PR adds a `just` helper command that performs a "refresh" of the local development database, which is a shortcut for running the following:
1. Wiping the DB of all data (`just db clean`)
2. Running migrations (`just migrate local`)
3. Seeding the database (`just db seed`)
With your containers running, you should be able to simply run `just db refresh`. Once complete, you should be able to log-in to the application locally and see that all user-created data has been wiped.
=> chore: add `just` command to refresh local database

refiner/app/main.py
This PR adds the [FastAPI GZipMiddleware](https://fastapi.tiangolo.com/advanced/middleware/#gzipmiddleware) so that the assets sent to the client are automatically compressed. This should greatly reduce the amount of data going over the wire to the client's browser.
I have tested this both locally and in the live demo environment. It appears to work as expected in both places.
The easiest way to test this is to locally compare this branch with `main`. Here are the steps to do that:
Starting from the top-level directory: `dibbs-ecr-refiner`
1. Run `cd client && npm run build` to create a `dist` directory within `client`
2. Run `mv dist ../refiner`
Now that you have a current production build, you can view this at [http://localhost:8080](http://localhost:8080). I'd recommend switching over …
=> chore: Add FastAPI GZip middleware

refiner/app/services/aws/s3.py
This PR addresses an issue where the `S3_ENDPOINT_URL` environment variable needed for localstack was marked as required. This variable does not need to be set in live environments.
1. Shut down your containers
2. Delete `S3_ENDPOINT_URL` from `docker-compose.yaml`
3. Start your containers up
4. You should see the application load up and work
=> fix: `S3_ENDPOINT_URL` should not need to be provided in a live environment

README.md, client/src/api/configurations/configurations.ts, client/src/api/schemas/associateCodesetResponse.ts, client/src/api/schemas/condition.ts, client/src/api/schemas/conditionEntry.ts, client/src/api/schemas/conditionProcessingInfo.ts, client/src/api/schemas/configurationCustomCodeResponse.ts, client/src/api/schemas/createConfigurationResponse.ts, client/src/api/schemas/dbConfigurationCustomCode.ts, client/src/api/schemas/dbTotalConditionCodeCount.ts, client/src/api/schemas/getConditionCode.ts, client/src/api/schemas/getConditionResponse.ts, client/src/api/schemas/getConditionsResponse.ts, client/src/api/schemas/getConfigurationResponse.ts, client/src/api/schemas/getConfigurationsResponse.ts, client/src/api/schemas/includedCondition.ts, client/src/api/schemas/refinedTestingDocument.ts, docker-compose.yaml, refiner/app/core/config.py, refiner/app/services/aws/s3.py, refiner/tests/conftest.py
This PR updates the app to accept an `S3_UPLOADED_FILES_BUCKET_NAME`, which is the bucket where user uploaded files will be stored. It was previously hard-coded to `refiner-app` but now that we're deploying to a live environment this won't suffice anymore.
> [!NOTE]
> Ignore the generated files. It looks like the latest changes may not have made it into a previous PR and should have. This is not related to the environment variable change.
Refined file downloading should continue to work locally as it did previously.
**Make sure to stop your containers and bring them up again so the environment variable gets loaded in**.
=> fix: accept S3 upload bucket name as an environment variable

refiner/app/services/aws/s3.py
This PR explicitly sets the S3 signature version to V4. This change is required to fix an error we were seeing when attempting to download KMS encrypted files.
[More detail here.](https://skylight-hq.slack.com/archives/C08H7EV6M37/p1758657045916439?thread_ts=1758649387.009659&cid=C08H7EV6M37)
- [Confirmed with Alis this works in the demo environment](https://skylight-hq.slack.com/archives/C08H7EV6M37/p1758748434427329?thread_ts=1758649387.009659&cid=C08H7EV6M37)
- You should see no change when downloading a refined file locally
=> fix: Explicitly set S3 signature version

refiner/tests/conftest.py, refiner/tests/integration/test_export.py
- Update the route in the test to include `/v1/`
- Update mock AWS region to `us-east-1` (arbitrary choice) so that localstack doesn't display a warning about an incorrect region being used
=> test: update integration test to use correct endpoint

README.md, refiner/scripts/README.md
1. 💬 fix: Use commands supported by Just 🏷️ 72d70a6
1. 💬 fix: Format using Prettier 🏷️ e212208
- n/a
- n/a
Read through the documentation and check if the commands run the same commands
that were originally there.
=> fix(docs): Update documentation around commands and format Markdown

client/src/components/Button/index.tsx, client/src/components/Diff/index.tsx, client/src/pages/Configurations/ConfigBuild/index.tsx, client/src/pages/Testing/RunTest.tsx
This PR updates all links that perform file downloads (and buttons that look like links) so that they all appear the same way. It also changes the `Export configuration` link from having the color `blue-cool-50` to `blue-cool-60`. This both solves an a11y issue I'm encountering as well as ensures all links now use the same color.
a11y issue I was seeing previously:
=> style: Make download link style consistent
